DROP TABLE IF EXISTS ORG_TBL;
DROP TABLE IF EXISTS GROUP_TBL;


CREATE TABLE ORG_TBL (
	id INT AUTO_INCREMENT PRIMARY KEY
	, label VARCHAR(40) NOT NULL
	, `desc` VARCHAR(150)
	, url VARCHAR(500) DEFAULT '#'
	, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	, modified TIMESTAMP
);

CREATE TABLE GROUP_TBL (
	id INT AUTO_INCREMENT PRIMARY KEY
	, org_id INTEGER NOT NULL
	, parent_id INTEGER
	, label VARCHAR(40) NOT NULL
	, `desc` VARCHAR(150)
	, thumb_img_name VARCHAR(256)
	, thumb_img_path VARCHAR(512)
	, url VARCHAR(500) DEFAULT '#'
	, created TIMESTAMP  DEFAULT CURRENT_TIMESTAMP  NOT NULL
	, modified TIMESTAMP 
);
