
DROP TABLE IF EXISTS GROUP_TBL;
DROP TABLE IF EXISTS ORG_TBL;


CREATE TABLE ORG_TBL (
	id INTEGER AUTO_INCREMENT PRIMARY KEY
	, label VARCHAR(40) NOT NULL
	, `desc` VARCHAR(150) DEFAULT ''
	, url VARCHAR(500) DEFAULT '#'
	, created TIMESTAMP  NOT NULL DEFAULT SYS_TIMESTAMP
	, modified TIMESTAMP
);

CREATE TABLE GROUP_TBL (
	id INTEGER AUTO_INCREMENT PRIMARY KEY
	, org_id INTEGER NOT NULL
	, parent_id INTEGER
	, label VARCHAR(40) NOT NULL
	, `desc` VARCHAR(150) DEFAULT ''
	, thumb_img_name VARCHAR(256)
	, thumb_img_path VARCHAR(512)
	, url VARCHAR(500) DEFAULT '#'
	, created TIMESTAMP   NOT NULL DEFAULT SYS_TIMESTAMP
	, modified TIMESTAMP 
);

ALTER TABLE GROUP_TBL
ADD FOREIGN KEY  (org_id)
REFERENCES ORG_TBL(id)
ON DELETE CASCADE;

ALTER TABLE GROUP_TBL
ADD FOREIGN KEY  (parent_id)
REFERENCES GROUP_TBL(id)
ON DELETE CASCADE;

